global:
  # replicas: 2
  env:
    NODE_ENV: development

zoo-frontend:
  image:
    tag: "0.0.0"
  ingress:
    hostTemplate: "zoo-dev.example.com"

zoo-backend:
  image:
    tag: "0.0.0"
  mongo:
    service:
      name: "zoo-mongo-dev-svc"
  ingress:
    hostTemplate: "api-zoo-dev.example.com"
